# Generated by Django 4.0.5 on 2022-07-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_student_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile_picture.jpeg', null=True, upload_to='profile_pictures/'),
        ),
    ]
